extends Node

const PLAYER_SHIP_SPEED = 150
const PLAYER_WALK_SPEED = 100
const PLAYER_STARTING_HEALTH = 5.0
const PLAYER_HIT_INVULN_IN_SECS = 1.5

const EYE_BOSS_STARTING_HEALTH = 50.0
const EYE_BOSS_EYE_BULLET_DAMAGE = 1.0

const ENERGY_TURRET_DAMAGE = 1.2

const MISSILE_DAMAGE = 1.5

const SPIDER_DAMAGE = 1.0